<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="mobile_base" params="robot_name">
        
        <xacro:property name="base_length" value="0.6" />
        <xacro:property name="base_width" value="0.4" />
        <xacro:property name="base_height" value="0.2" />
        <xacro:property name="wheel_radius" value="0.1" />
        <xacro:property name="wheel_length" value="0.05" />

        <link name="${robot_name}_base_footprint" />

        <link name="${robot_name}_base_link">
            <visual>
                <geometry>
                    <box size="${base_length} ${base_width} ${base_height}" />
                </geometry>
                <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
                <material name="green" />
            </visual>
             <collision>
                <geometry>
                    <box size="${base_length} ${base_width} ${base_height}" />
                </geometry>
                <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            </collision>
            <xacro:box_inertia m="5.0" x="${base_length}" y="${base_width}" z="${base_height}" o_xyz="0 0 ${base_height / 2.0}" o_rpy="0 0 0" />
        </link>

        <xacro:macro name="wheel_link" params="prefix robot_name">
            <link name="${robot_name}_${prefix}_wheel_link">
                <visual>
                    <geometry>
                        <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                    </geometry>
                    <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                    <material name="gray" />
                </visual>
                <collision>
                    <geometry>
                        <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                    </geometry>
                    <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                </collision>
                <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" l="${wheel_length}" o_xyz="0 0 0" o_rpy="${pi / 2.0} 0 0" />
            </link>
        </xacro:macro>

        <xacro:wheel_link prefix="right" robot_name="${robot_name}" />
        <xacro:wheel_link prefix="left" robot_name="${robot_name}" />

        <link name="${robot_name}_caster_wheel_link">
            <visual>
                <geometry>
                    <sphere radius="${wheel_radius / 2.0}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <material name="gray" />
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${wheel_radius / 2.0}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
            </collision>
            <xacro:sphere_inertia m="0.5" r="${wheel_radius / 2.0}" 
                                  o_xyz="0 0 0" o_rpy="0 0 0" />
        </link>

        <joint name="${robot_name}_base_joint" type="fixed">
            <parent link="${robot_name}_base_footprint" />
            <child link="${robot_name}_base_link" />
            <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
        </joint>

        <joint name="${robot_name}_base_right_wheel_joint" type="continuous">
            <parent link="${robot_name}_base_link" />
            <child link="${robot_name}_right_wheel_link" />
            <origin xyz="${-base_length / 4.0} ${-(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
            <axis xyz="0 1 0" />
        </joint>

        <joint name="${robot_name}_base_left_wheel_joint" type="continuous">
            <parent link="${robot_name}_base_link" />
            <child link="${robot_name}_left_wheel_link" />
            <origin xyz="${-base_length / 4.0} ${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
            <axis xyz="0 1 0" />
        </joint>

        <joint name="${robot_name}_base_caster_wheel_joint" type="fixed">
            <parent link="${robot_name}_base_link" />
            <child link="${robot_name}_caster_wheel_link" />
            <origin xyz="${base_length / 3.0} 0 ${-wheel_radius / 2.0}" rpy="0 0 0" />
        </joint>
        
    </xacro:macro>

</robot>