# Robot 1 bridges
- ros_topic_name: "/robot_1/cmd_vel"
  gz_topic_name: "/model/robot_1/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

- ros_topic_name: "/robot_1/joint_states"
  gz_topic_name: "/world/empty/model/robot_1/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

- ros_topic_name: "/pose_info"
  gz_topic_name: "/world/empty/dynamic_pose/info"
  ros_type_name: "geometry_msgs/msg/PoseArray"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

# Robot 2 bridges
- ros_topic_name: "/robot_2/cmd_vel"
  gz_topic_name: "/model/robot_2/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

- ros_topic_name: "/robot_2/joint_states"
  gz_topic_name: "/world/empty/model/robot_2/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

# # Robot 3 bridges
# - ros_topic_name: "/robot_3/cmd_vel"
#   gz_topic_name: "/model/robot_3/cmd_vel"
#   ros_type_name: "geometry_msgs/msg/Twist"
#   gz_type_name: "gz.msgs.Twist"
#   direction: ROS_TO_GZ

# - ros_topic_name: "/robot_3/joint_states"
#   gz_topic_name: "/world/empty/model/robot_3/joint_state"
#   ros_type_name: "sensor_msgs/msg/JointState"
#   gz_type_name: "gz.msgs.Model"
#   direction: GZ_TO_ROS


# Clock bridge
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS