# Robot 1 bridges
# Remember: Change the gz topic link when the world changes
- ros_topic_name: "/robot_1/cmd_vel"
  gz_topic_name: "/model/robot_1/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

# Robot 1 LiDAR sensors
- ros_topic_name: "/robot_1/scan_front"
  gz_topic_name: "/world/world_demo/model/robot_1/link/scan_front/sensor/scan_front/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "/robot_1/scan_back"
  gz_topic_name: "/world/world_demo/model/robot_1/link/scan_back/sensor/scan_back/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "/robot_1/scan_omni"
  gz_topic_name: "/world/world_demo/model/robot_1/link/scan_omni/sensor/scan_omni/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

# Robot 1 main scan topic (combined or primary) - choose one of the above
- ros_topic_name: "/robot_1/scan"
  gz_topic_name: "/world/world_demo/model/robot_1/link/scan_omni/sensor/scan_omni/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

# Robot 1 Odometry
- ros_topic_name: "/robot_1/odom"
  gz_topic_name: "/model/robot_1/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

# Robot 1 IMU (useful for navigation)
- ros_topic_name: "/robot_1/imu"
  gz_topic_name: "/world/world_demo/model/robot_1/link/imu_link/sensor/imu/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

# Robot 1 TF (Transform information)
- ros_topic_name: "/robot_1/tf_gazebo"
  gz_topic_name: "/model/robot_1/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

# Robot 2 bridges
- ros_topic_name: "/robot_2/cmd_vel"
  gz_topic_name: "/model/robot_2/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

# Robot 2 LiDAR sensors
- ros_topic_name: "/robot_2/scan_front"
  gz_topic_name: "/world/world_demo/model/robot_2/link/scan_front/sensor/scan_front/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "/robot_2/scan_back"
  gz_topic_name: "/world/world_demo/model/robot_2/link/scan_back/sensor/scan_back/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "/robot_2/scan_omni"
  gz_topic_name: "/world/world_demo/model/robot_2/link/scan_omni/sensor/scan_omni/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

# Robot 2 main scan topic (combined or primary) - choose one of the above
- ros_topic_name: "/robot_2/scan"
  gz_topic_name: "/world/world_demo/model/robot_2/link/scan_omni/sensor/scan_omni/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

# Robot 2 Odometry
- ros_topic_name: "/robot_2/odom"
  gz_topic_name: "/model/robot_2/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

# Robot 2 IMU (useful for navigation)
- ros_topic_name: "/robot_2/imu"
  gz_topic_name: "/world/world_demo/model/robot_2/link/imu_link/sensor/imu/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

# Robot 2 TF (Transform information)
- ros_topic_name: "/robot_2/tf_gazebo"
  gz_topic_name: "/model/robot_2/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

# Shared topics
- ros_topic_name: "/pose_info"
  gz_topic_name: "/world/world_demo/dynamic_pose/info"
  ros_type_name: "geometry_msgs/msg/PoseArray"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

# Clock bridge
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS